import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { IntegrationWallets } from '../components/Wallet/IntegratedWallets'
import MessageBox from '../components/MessgeBox/MessageBox'
import { useContextAPI } from '../lib/contextapi'
import { useWeb3React } from '@web3-react/core'
import { useState } from 'react'
import { createCollection } from '../lib/createSchema'
import { insertDataMember } from '../lib/polybasesdk'
import { pageContractAddress, pageContractjson } from '../smartContractData/coffeeContract'
import { ethers } from 'ethers'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { imagescollection } from '../lib/imagescollection'
import Avatar from 'avataaars'
import HomePage from "./../components/Home"

export default function index() {

  return (
    <div className='bg-light' style={{minHeight: "100vh"}}>
      <Head>
        <title>Buymeacoffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />

    </div>
  )
}
